[package]
name = "erth-exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["blocking", "rustls-tls"], default-features = false }
scraper = "0.20.0"
